networks:
  tanner_local:

services:

# Tanner Redis Service
  tanner_redis:
    build: ./redis
    container_name: tanner_redis
    restart: on-failure
    stop_signal: SIGKILL
    tty: true
#    cpu_count: 1
#    cpus: 0.25
    networks:
     - tanner_local
    image: "dtagdevsec/redis:24.04"
    read_only: true

# PHP Sandbox service
  tanner_phpox:
    build: ./phpox
    container_name: tanner_phpox
    restart: on-failure
    stop_signal: SIGKILL
    tmpfs:
     - /tmp:uid=2000,gid=2000
    tty: true
#    cpu_count: 1
#    cpus: 0.25
    networks:
     - tanner_local
    image: "dtagdevsec/phpox:24.04"
    read_only: true

# Tanner Service
  tanner:
    build: 
      context: ../
      dockerfile: docker/tanner/Dockerfile
    container_name: tanner
    restart: on-failure
    stop_signal: SIGKILL
    tty: true
#    cpu_count: 1
#    cpus: 0.25
    networks:
     - tanner_local
    image: "dtagdevsec/tanner:24.04"
    command: tanner
    read_only: true
    volumes:
     - $HOME/web-honeypot/data/tanner/data:/var/log/tanner
     - $HOME/web-honeypot/data/tanner/files:/opt/tanner/files
    depends_on:
     - tanner_phpox

# Snare Service
  snare:
    build: 
      context: ../
      dockerfile: docker/snare/Dockerfile
    container_name: snare
    restart: on-failure
    stop_signal: SIGKILL
    tty: true
#    cpu_count: 1
#    cpus: 0.25
    networks:
     - tanner_local
    ports:
     - "80:80"
    image: "dtagdevsec/snare:24.04"
    depends_on:
     - tanner
    volumes:
     - $HOME/web-honeypot/data/snare/log:/var/log/snare
     - $HOME/credentials.xlsx:/opt/snare/files/credentials.xlsx
     - ./snare/dist/honeytokens:/opt/snare/honeytokens
