name: Build and Deploy to Azure Container Apps

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up SSH key
      run: |
        echo "${{ secrets.AZURE_VM_SSH_PRIVATE_KEY }}" > private_key.pem
        chmod 600 private_key.pem

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.AZURE_LOGIN_SERVER }}.azurecr.io/log_collector:latest
        file: ./Dockerfile

    - name: Deploy to Azure Container Apps
      uses: azure/aci-deploy@v1
      with:
        resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
        dns-name-label: log-collector-app
        location: 'northeurope'
        name: log-collector-app
        image: ${{ secrets.AZURE_LOGIN_SERVER }}.azurecr.io/log_collector:latest
        registry-login-server: ${{ secrets.AZURE_LOGIN_SERVER }}.azurecr.io
        registry-username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        registry-password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
        environment-variables: |
          AZURE_STORAGE_CONNECTION_STRING=${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          CONTAINER_NAME=log_collector
          SFTP_HOST=${{ secrets.AZURE_VM_IP }}
          SFTP_PORT=${{ secrets.AZURE_SFTP_PORT }}
          SFTP_USERNAME=${{ secrets.SFTP_USERNAME }}
          SSH_PRIVATE_KEY_PATH=private_key.pem
          LOG_FILES=${{ secrets.LOG_FILES }}