name: Restart and Deploy Honeypot on Azure VM

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to deploy'
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  restart-vm:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Restart Azure VM
        run: |
          az vm restart --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AZURE_VM_NAME }}
      
      - name: Set Tag Name
        id: set-tag
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "TAG_NAME=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
            echo "::set-output name=tag_name::${{ github.event.inputs.tag }}"
          else
            echo "TAG_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV
            echo "::set-output name=tag_name::${TAG_NAME}"
          fi
    outputs:
      tag_name: ${{ steps.set-tag.outputs.tag_name }}
  
  deploy-honeypot:
    runs-on: ubuntu-latest
    needs: restart-vm
    env:
      TAG_NAME: ${{ needs.restart-vm.outputs.tag_name }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Transfer Files to Azure VM via SCP
        run: |
          # Create a temporary private key file for the SCP command
          echo "${{ secrets.AZURE_VM_SSH_PRIVATE_KEY }}" > /tmp/private_key.pem
          chmod 600 /tmp/private_key.pem

          # Use SCP to copy files
          scp -o StrictHostKeyChecking=no -i /tmp/private_key.pem -r ${{ github.workspace }}/* azureuser@${{ secrets.AZURE_VM_IP }}:/home/azureuser/thesis_honeypot/${{ env.TAG_NAME }}

          # Clean up the private key file
          rm /tmp/private_key.pem
  
      - name: Deploy Application
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          key: ${{ secrets.AZURE_VM_SSH_PRIVATE_KEY }}
          script: |
            # Stop and remove all Docker containers and images
            sudo docker stop $(sudo docker ps -q)
            sudo docker rm $(sudo docker ps -aq)
            sudo docker rmi $(sudo docker images -q)
            sudo docker volume prune -f

            # Ensure log files exist as files before starting Docker
            sudo mkdir -p /home/azureuser/log/snare
            sudo mkdir -p /home/azureuser/log/tanner
            sudo mkdir -p /home/azureuser/thesis_honeypot/${{ env.TAG_NAME }}/docker/snare/dist/honeytokens
            
            sudo touch /home/azureuser/thesis_honeypot//${{ env.TAG_NAME }}/logging/webhooks.json
            sudo touch /home/azureuser/log/snare/snare.log
            sudo touch /home/azureuser/log/snare/snare.err
            sudo touch /home/azureuser/log/tanner/tanner.log
            sudo touch /home/azureuser/log/tanner/tanner.err
            sudo touch /home/azureuser/log/tanner/tanner_report.json
            sudo chown -R 2000:2000 /home/azureuser/log/snare
            sudo chown -R 2000:2000 /home/azureuser/log/tanner
            sudo chown -R 2000:2000 /home/azureuser/thesis_honeypot/${{ env.TAG_NAME }}/docker/snare/dist/honeytokens
            sudo chmod -R 755 /home/azureuser/thesis_honeypot/${{ env.TAG_NAME }}/docker/snare/dist/honeytokens
            sudo chmod -R 755 /home/azureuser/log/snare
            sudo chmod -R 755 /home/azureuser/log/tanner
            
            # Start the Docker containers
            cd /home/azureuser/thesis_honeypot/${{ env.TAG_NAME }}/docker
            sudo docker compose up -d --build
