name: Build and Deploy to Azure Container Apps

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Login to Azure Container Registry
      run: |
        echo ${{ secrets.AZURE_REGISTRY_PASSWORD }} | docker login ${{ secrets.AZURE_LOGIN_SERVER }} -u ${{ secrets.AZURE_REGISTRY_USERNAME }} --password-stdin
    
    - name: Build and Push Docker Image
      run: |
        docker build -f docker/logging/Dockerfile -t ${{ secrets.AZURE_LOGIN_SERVER }}/log_collector:${{ github.sha }} .
        docker push ${{ secrets.AZURE_LOGIN_SERVER }}/log_collector:${{ github.sha }}

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: |
          ${{ secrets.AZURE_VM_SSH_PRIVATE_KEY }}
    
    - name: Create Container App Environment
      run: |
        az extension add --name containerapp --upgrade
        az containerapp env create -n log-collector-app-env -g ${{ secrets.AZURE_RESOURCE_GROUP }} -l northeurope
  
    - name: Deploy to Azure Container Apps
      run: |
          az containerapp create -n log-collector-app -g ${{ secrets.AZURE_RESOURCE_GROUP }} --environment log-collector-app-env --image ${{ secrets.AZURE_LOGIN_SERVER }}/log_collector:${{ github.sha }} --env-vars AZURE_STORAGE_CONNECTION_STRING=${{ secrets.AZURE_STORAGE_CONNECTION_STRING }} CONTAINER_NAME=log_collector SFTP_HOST=${{ secrets.AZURE_VM_IP }} SFTP_PORT=${{ secrets.AZURE_SFTP_PORT }} SFTP_USERNAME=${{ secrets.AZURE_VM_USERNAME }} SSH_AUTH_SOCK=${SSH_AUTH_SOCK} LOG_FILES=${{ secrets.LOG_FILES }} --ingress disabled